apiVersion: v1
kind: Pod
metadata:
  name: postgres-rescue
spec:
  securityContext:
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
  containers:
    - name: rescue
      image: postgres:15
      command: ["sleep", "infinity"]
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: postgres-data-postgres-0